# @package _global_

n_iterations: 10

exp_config_args:
  _target_: core.types.ExperimentConfig

  max_retries: 3

  preamble: >-
    You are a Kaggle grandmaster competing in a competition.

  task_description_file: description.md

  code_instructions: >-
    Write a single file called solution.py that does the following:\n
      - Loads the training data from os.environ['TRAIN_DATA_PATH']\n
      - Loads the test data from os.environ['TEST_DATA_PATH']\n
      - It is important your code references the training and test data paths exactly as above,
        via these environment variables, which will already be set correctly for you.\n
      - Performs any arbitrary training and evaluation logic on this data split.
        For example, you might hold out some subset of this data for the purposes
        of k-fold cross validation for model and hyperparameter selection.\n
      - Finally, evaluates the final model on the test data and writes the results
        to a file in the current directory called submission.csv.\n
    
    Besides solution.py, you may not create any extra files or modify any other files
    in the directory.

    Your code will be run on a machine with a single H100 GPU.

  entry_fname: solution.py
  fnames: 
    - 'solution.py'

  eval_fname: grader.py

  metric_types:
    score: float
    total_medals: int
    total_gold_medals: int
    total_silver_medals: int
    total_bronze_medals: int
    total_above_median: int

  selection_metric: total_medals
  lower_is_better: false

slurm_config_args:
  _target_: core.types.SlurmConfig

  nodes: 1
  tasks_per_node: 1
  gpus_per_node: 1
  cpus_per_task: 12
  job_ttl: 30
  job_name: mlebench
  account: maui
